name: CI - OWASP ZAP

on:
  push:
  pull_request:

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        working-directory: app
        run: npm ci

      - name: Start app (localhost:8080)
        working-directory: app
        run: |
          nohup npm start >/tmp/app.log 2>&1 &
          npx wait-on http://localhost:8080

      - name: Prepare reports folder
        run: mkdir -p zap-reports

      - name: Run OWASP ZAP full scan (Docker)
        run: |
          docker run --rm --network=host                     -v "${{ github.workspace }}/zap-reports":/zap/wrk/:rw                     ghcr.io/zaproxy/zaproxy:stable                     zap-full-scan.py                       -t http://localhost:8080                       -r zap-report.html                       -J zap-report.json                       -w zap-report.md                       -I

      - name: Print short log
        run: |
          echo "==== Server stdout (tail) ===="
          tail -n 100 /tmp/app.log || true

      - name: Analyze ZAP JSON and fail on High/Critical
        run: |
          python3 scripts/parse_zap_report.py zap-reports/zap-report.json

      - name: Upload ZAP artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zap-reports
          path: zap-reports
